#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot violin plots of phenotype distributions for top importance loci.

Input:
  - long-format table generated by importance_genotype_and_phenotype_distribution.py

Output:
  - one PNG/PDF per locus
  - genotype count/proportion shown below each category
  - optional t-test between top two genotype groups by sample count
"""

import argparse
import math
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot genotype-phenotype violin plots for top importance loci"
    )
    parser.add_argument(
        "--long-table",
        required=True,
        help="Long-format TSV from extraction script"
    )
    parser.add_argument(
        "--outdir",
        default="violin_plots",
        help="Output directory"
    )
    parser.add_argument(
        "--min-group-size",
        type=int,
        default=5,
        help="Minimum sample size per genotype group to plot (default: 5)"
    )
    parser.add_argument(
        "--top-genotypes",
        type=int,
        default=2,
        help="How many genotype groups to show per locus, ranked by count (default: 2)"
    )
    return parser.parse_args()


def fmt_pvalue(p: float) -> str:
    if pd.isna(p):
        return "NA"
    if p < 1e-300:
        return "<1e-300"
    return f"{p:.2e}"


def sanitize_filename(s: str) -> str:
    return "".join(c if c.isalnum() or c in "._-" else "_" for c in s)


def plot_one_locus(df_locus: pd.DataFrame, outdir: str, min_group_size: int, top_genotypes: int):
    locus_id = df_locus["locus_id"].iloc[0]
    display_locus_id = locus_id.rsplit("-", 1)[0]
    trait = df_locus["trait"].iloc[0]
    chrom = df_locus["chr"].iloc[0]
    pos = df_locus["pos"].iloc[0]
    ref = df_locus["ref"].iloc[0]
    alt = df_locus["alt"].iloc[0]
    rank = df_locus["rank"].iloc[0]

    df = df_locus.copy()
    df = df[df["genotype"] != "NA"].copy()
    df = df[pd.notna(df["phenotype"])].copy()

    if df.empty:
        return

    count_df = (
        df.groupby("genotype")["sample"]
        .nunique()
        .rename("n")
        .reset_index()
        .sort_values("n", ascending=False)
    )

    count_df = count_df[count_df["n"] >= min_group_size].head(top_genotypes).copy()
    keep_genotypes = count_df["genotype"].tolist()

    if len(keep_genotypes) < 2:
        return

    df = df[df["genotype"].isin(keep_genotypes)].copy()
    total_n = df["sample"].nunique()

    genotype_order = (
        df.groupby("genotype")["sample"]
        .nunique()
        .sort_values(ascending=False)
        .index
        .tolist()
    )

    data = [df.loc[df["genotype"] == g, "phenotype"].values for g in genotype_order]
    ns = [len(x) for x in data]
    props = [n / total_n * 100.0 for n in ns]

    # t-test between top 2 groups
    pval = np.nan
    if len(data) >= 2:
        try:
            _, pval = ttest_ind(data[0], data[1], equal_var=False, nan_policy="omit")
        except Exception:
            pval = np.nan

    fig, ax = plt.subplots(figsize=(3.2, 3.2), dpi=300)

    colors = ["#5E75A6", "#729ece", "#CD3B2C", "#D97A6F"]
    violin_parts = ax.violinplot(
        data,
        positions=np.arange(1, len(data) + 1),
        widths=0.8,
        showmeans=False,
        showmedians=False,
        showextrema=False,
    )

    for i, body in enumerate(violin_parts["bodies"]):
        body.set_facecolor(colors[i % len(colors)])
        body.set_edgecolor("black")
        body.set_linewidth(0.5)
        body.set_alpha(1.0)

    # boxplot overlay
    box = ax.boxplot(
        data,
        positions=np.arange(1, len(data) + 1),
        widths=0.25,
        patch_artist=True,
        showfliers=False,
        medianprops=dict(color="black", linewidth=0.8),
        whiskerprops=dict(color="black", linewidth=0.6),
        capprops=dict(color="black", linewidth=0.6),
        boxprops=dict(facecolor="white", edgecolor="black", linewidth=0.6),
    )

    ax.set_xticks(np.arange(1, len(data) + 1))
    ax.set_xticklabels(genotype_order, fontsize=10, fontweight="bold")
    ax.set_xlabel("Genotype", fontsize=11, fontweight="bold")
    ax.set_ylabel(trait, fontsize=11, fontweight="bold")

    ymin, ymax = ax.get_ylim()
    yr = ymax - ymin
    ax.set_ylim(ymin, ymax + yr * 0.15)

    ymin, ymax = ax.get_ylim()
    yr = ymax - ymin
    ax.set_ylim(ymin - yr * 0.12, ymax + yr * 0.15)

    ymin, ymax = ax.get_ylim()
    yr = ymax - ymin

    label_y = ymin + yr * 0.03
    for i, (n, prop) in enumerate(zip(ns, props), start=1):
        ax.text(
            i,
            label_y,
            f"n = {n} ({prop:.0f}%)",
            ha="center",
            va="bottom",
            fontsize=9
        )

    # p-value bracket for top two groups：放在上方留白区域中
    if len(data) >= 2 and pd.notna(pval):
        x1, x2 = 1, 2
        y = ymax - yr * 0.09
        h = yr * 0.03

        ax.plot(
            [x1, x1, x2, x2],
            [y, y + h, y + h, y],
            color="black",
            linewidth=0.6
        )
        # p-value label: italic p, normal numeric value
        x_mid = (x1 + x2) / 2
        y_text = y + h + yr * 0.015

        ax.text(
            x_mid,
            y_text,
            "p = ",
            ha="right",
            va="bottom",
            fontsize=9,
            fontweight="bold",
            fontstyle="italic"
        )
        ax.text(
            x_mid,
            y_text,
            f"{fmt_pvalue(pval)}",
            ha="left",
            va="bottom",
            fontsize=9,
            fontweight="bold",
            fontstyle="normal"
        )
    title = f"Rank{rank} {display_locus_id} ({ref}>{alt})"
    ax.set_title(title, fontsize=10)

    # clean style
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_linewidth(1.0)
    ax.spines["bottom"].set_linewidth(1.0)
    ax.tick_params(axis="both", width=1.0, length=3)

    plt.tight_layout()

    png = os.path.join(outdir, sanitize_filename(f"{trait}.{rank}.{locus_id}.png"))
    pdf = os.path.join(outdir, sanitize_filename(f"{trait}.{rank}.{locus_id}.pdf"))
    fig.savefig(png, dpi=300, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)


def main():
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    df = pd.read_csv(args.long_table, sep="\t")
    required = {"trait", "rank", "locus_id", "genotype", "phenotype", "sample"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns in long table: {missing}")

    for locus_id, subdf in df.groupby("locus_id", sort=False):
        plot_one_locus(
            subdf,
            outdir=args.outdir,
            min_group_size=args.min_group_size,
            top_genotypes=args.top_genotypes
        )

    print(f"[OK] Plots saved to: {args.outdir}")


if __name__ == "__main__":
    main()