output_dir: 705rice_conv_mha_train_out
data:
  geno_file: /home/gulei/projects/Aquila-GS/case/705rice_0.03.full.all.impute.biallelic.vcf.gz
  pheno_file: /home/gulei/projects/Aquila-GS/case/GSTP008.pheno.tsv
  encoding_type: diploid_onehot
  variant_type: snp
  classification_tasks: null
train:
  batch_size: 16
  num_epochs: 286
  learning_rate: 0.00011234467414769698
  weight_decay: 3.003629953998308e-06
  optimizer_type: adamw
  loss_type: mse
  normalize_regression: true
  uncertainty_weighting: true
  early_stopping_patience: 40
  gradient_clip_norm: 2.0
  scheduler_type: cosine_warmup
  scheduler_params:
    warmup_epochs: 20
    warmup_start_factor: 0.0013048552115558078
    min_lr: 2.714938768367449e-07
  val_split: 0.1
  test_split: 0.0
  num_workers: 4
model:
  architecture_type: single
  activation: gelu
  dropout: 0.1
  l2_scale: 0.00020433917063777745
  verbose: true
  embedder:
  - name: conv_block
    in_channels: 8
    out_channels: 256
    kernel_size: 13
    activation: gelu
    norm_type: layer
    residual: false
  trunk:
  - name: down_conv_tower
    in_channels: 256
    out_channels: 256
    kernel_size: 5
    padding: 2
    activation: gelu
    dropout: 0.31142607748843276
    norm_type: layer
    order: nac
    residual: true
    seq_len_threshold: 1500
  - name: transformer
    d_model: 256
    num_heads: 8
    d_ff: 256
    dropout: 0.16404700611736586
    activation: gelu
    kernel_size: 3
  - name: multi_head_pool
    d_model: 256
    num_heads: 4
    dropout: 0.3858921951464802
    pool_axis: 2
    kernel_size: 5
  heads:
    regression:
    - name: regression_head
      in_features: null
      num_targets: 18
      hidden_features: 128
      dropout: 0.4095498862768971
      activation: gelu
